parallel_tools.py: `SyncAsyncPool` no longer subclasses `multiprocessing.Pool`. - Avoids overcomplication, fixes warning message.   - `AttributeError: 'SyncAsyncPool' object has no attribute '_state'`